name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "48 3 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_achievements: yes
          plugin_languages: yes
          plugin_reactions: yes
          plugin_calendar: yes
          plugin_traffic: yes
          
      - uses: lowlighter/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: terminal
          filename: metrics.terminal.svg
          base: header, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_achievements: yes
          plugin_languages: yes
          plugin_reactions: yes
          plugin_calendar: yes
          plugin_traffic: yes
